# services:
  # api:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_HTTPS_PORTS=8081
  #     - ConnectionStrings__DefaultConnection=User ID=postgres;Password=supersecretpassword;Host=db;Port=5432;Database=boilerplatedb;Pooling=true;Connection Lifetime=0;
  #   ports:
  #     - "8080"
  #     - "8081"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro